#!/usr/bin/env bash
set -euo pipefail
if [[ "${RAYMAN_DEBUG:-0}" == "1" ]]; then set -x; fi

ROOT="$(pwd)"

resolve_requirements_helper() {
  local helper_name="$1"
  local primary="./.Rayman/scripts/requirements/${helper_name}"
  local dist="./.Rayman/.dist/scripts/requirements/${helper_name}"

  if [[ -f "${primary}" ]]; then
    echo "${primary}"
    return 0
  fi
  if [[ -f "${dist}" ]]; then
    mkdir -p "$(dirname "${primary}")"
    # Backfill helper into workspace scripts so nested helper calls remain stable.
    cp -f "${dist}" "${primary}" 2>/dev/null || true
    if [[ -f "${primary}" ]]; then
      echo "${primary}"
      return 0
    fi
    echo "${dist}"
    return 0
  fi
  return 1
}

DETECT_SOLUTION_SCRIPT="$(resolve_requirements_helper "detect_solution.sh" || true)"
if [[ -z "${DETECT_SOLUTION_SCRIPT}" ]]; then
  echo "[req] missing helper script: detect_solution.sh (.Rayman/scripts or .Rayman/.dist/scripts)" >&2
  exit 127
fi

SOL="$(bash "${DETECT_SOLUTION_SCRIPT}")"
SOL_DIR=".${SOL}"
# all requirements stay under .<SolutionName>/
SOL_REQ="${SOL_DIR}/.${SOL}.requirements.md"
PROJ_LIST_HEADER="## Project requirements 列表（必须逐一遵守）"
AGENTIC_HEADER="## Agentic Docs（默认 pipeline 硬门禁）"

mkdir -p "${SOL_DIR}"

DETECT_PROJECTS_SCRIPT="$(resolve_requirements_helper "detect_projects.sh" || true)"
if [[ -n "${DETECT_PROJECTS_SCRIPT}" ]]; then
  mapfile -t PROJS < <(bash "${DETECT_PROJECTS_SCRIPT}" || true)
else
  echo "[req] helper missing, skip project detection: detect_projects.sh" >&2
  PROJS=()
fi
TEMPLATE_PRIMARY="${ROOT}/.Rayman/templates/requirements.project.template.md"
TEMPLATE_DIST="${ROOT}/.Rayman/.dist/templates/requirements.project.template.md"
TEMPLATE=""
TEMPLATE_SOURCE="builtin-fallback"

if [[ -f "${TEMPLATE_PRIMARY}" ]]; then
  TEMPLATE="${TEMPLATE_PRIMARY}"
  TEMPLATE_SOURCE="workspace-template"
elif [[ -f "${TEMPLATE_DIST}" ]]; then
  TEMPLATE="${TEMPLATE_DIST}"
  TEMPLATE_SOURCE="dist-template"
fi

echo "[req] template source: ${TEMPLATE_SOURCE}"

render_project_template() {
  local project_name="$1"
  if [[ -n "${TEMPLATE}" && -f "${TEMPLATE}" ]]; then
    local escaped
    escaped="$(printf '%s' "${project_name}" | sed -e 's/[\/&]/\\&/g')"
    sed "s/{{PROJECT_NAME}}/${escaped}/g" "${TEMPLATE}"
    return 0
  fi

  cat <<EOF
# ${project_name} 项目 Requirements（强制约束）

## 项目范围
- 本文件定义 **${project_name}** 项目的强制约束规则。
- 任何涉及该项目的代码修改 / 测试执行，都必须遵守本文件。

## 必须遵守的规则（请按项目实际补充）
- （示例）不得随意修改公共 API（除非同步更新依赖项目）
- （示例）新增依赖必须说明原因与替代方案
- （示例）涉及配置变更必须同步更新部署/运行文档

## 测试要求（请按项目实际补充）
- （示例）修改必须通过现有测试
- （示例）新增行为必须补充测试用例

## 附件（可选，支持复杂操作）
- 允许在本项目 requirements 旁边添加附件文件（例如：截图、操作步骤、脚本片段、示例输入输出）。
- 建议放在同目录的 \`attachments/\` 下，并在此处列出相对路径与用途。
- **注意：附件是 requirements 的一部分**，涉及修改时需同步更新。

## 功能需求（来自Prompt，自动维护）

<!-- RAYMAN:AUTOGEN: marker blocks are managed automatically -->

## 验收标准（来自Prompt，自动维护）

<!-- RAYMAN:AUTOGEN: marker blocks are managed automatically -->

## 附件（来自Prompt，自动维护，可手工追加）

<!-- RAYMAN:AUTOGEN: marker blocks are managed automatically -->
EOF
}

ensure_agentic_artifacts() {
  local agentic_dir="${SOL_DIR}/agentic"
  mkdir -p "${agentic_dir}"

  if [[ ! -f "${agentic_dir}/evals.md" ]]; then
    cat > "${agentic_dir}/evals.md" <<'EOF'
# Rayman Agentic Evals

- planner_prompt: tracked by `.github/prompts/*.prompt.md` and `plan.current.*`
- reflection_prompt: tracked by `reflection.current.*`
- grader_targets:
  - doc gate pass
  - acceptance closed
  - reflection outcome distribution
  - first-pass stability after planner_v1 rollout
- latest_result: pending
- baseline: pending more than one sample
EOF
  fi

  if [[ ! -f "${agentic_dir}/plan.current.md" ]]; then
    cat > "${agentic_dir}/plan.current.md" <<'EOF'
# Rayman Agentic Plan

- status: placeholder
- note: generated by `dispatch` when `RAYMAN_AGENT_PIPELINE=planner_v1`
EOF
  fi

  if [[ ! -f "${agentic_dir}/plan.current.json" ]]; then
    cat > "${agentic_dir}/plan.current.json" <<'EOF'
{
  "schema": "rayman.agentic.plan.v1",
  "status": "placeholder"
}
EOF
  fi

  if [[ ! -f "${agentic_dir}/tool-policy.md" ]]; then
    cat > "${agentic_dir}/tool-policy.md" <<'EOF'
# Rayman Tool Policy

- status: placeholder
- note: generated by `dispatch` when `RAYMAN_AGENT_PIPELINE=planner_v1`
EOF
  fi

  if [[ ! -f "${agentic_dir}/tool-policy.json" ]]; then
    cat > "${agentic_dir}/tool-policy.json" <<'EOF'
{
  "schema": "rayman.agentic.tool_policy.v1",
  "status": "placeholder"
}
EOF
  fi

  if [[ ! -f "${agentic_dir}/reflection.current.md" ]]; then
    cat > "${agentic_dir}/reflection.current.md" <<'EOF'
# Rayman Reflection

- status: placeholder
- note: generated by `review-loop` when `RAYMAN_AGENT_PIPELINE=planner_v1`
EOF
  fi

  if [[ ! -f "${agentic_dir}/reflection.current.json" ]]; then
    cat > "${agentic_dir}/reflection.current.json" <<'EOF'
{
  "schema": "rayman.agentic.reflection.v1",
  "status": "placeholder"
}
EOF
  fi
}

build_agentic_docs_file() {
  local out_file="$1"
  cat > "${out_file}" <<EOF
- ${SOL_DIR}/agentic/plan.current.md
- ${SOL_DIR}/agentic/plan.current.json
- ${SOL_DIR}/agentic/tool-policy.md
- ${SOL_DIR}/agentic/tool-policy.json
- ${SOL_DIR}/agentic/reflection.current.md
- ${SOL_DIR}/agentic/reflection.current.json
- ${SOL_DIR}/agentic/evals.md
EOF
}

for p in "${PROJS[@]}"; do
  pd="${SOL_DIR}/.${p}"
  pf="${pd}/.${p}.requirements.md"
  mkdir -p "${pd}"
  if [[ ! -f "${pf}" ]]; then
    render_project_template "${p}" > "${pf}"
    echo "[req] wrote: ${pf}"
  fi
done

ensure_agentic_artifacts

# Migrate legacy requirements (root layout) into new structure (idempotent)
MIGRATE_REQUIREMENTS_SCRIPT="$(resolve_requirements_helper "migrate_legacy_requirements.sh" || true)"
if [[ -n "${MIGRATE_REQUIREMENTS_SCRIPT}" ]]; then
  bash "${MIGRATE_REQUIREMENTS_SCRIPT}" || true
else
  echo "[req] helper missing, skip migration: migrate_legacy_requirements.sh" >&2
fi

build_project_list_file() {
  local out_file="$1"
  local count=0
  : > "${out_file}"
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    rel="${f#./}"
    [[ "$rel" == "${SOL_REQ#./}" ]] && continue
    echo "- ${rel}" >> "${out_file}"
    count=$((count + 1))
  done < <(find "${SOL_DIR}" -maxdepth 3 -type f -name ".*.requirements.md" | sort)

  if [[ "${count}" -eq 0 ]]; then
    echo "- (none detected)" >> "${out_file}"
  fi
}

write_solution_requirements() {
  local project_list_file="$1"
  local agentic_docs_file="$2"
  {
    echo "# ${SOL} Solution Requirements（强制约束）"
    echo
    echo "## 必须先读这个文件"
    echo "- 本文件为 Solution 级强制约束，必须执行。"
    echo "- 本文件必须包含全部 Project requirements（按路径文本列出）。"
    echo
    echo "${PROJ_LIST_HEADER}"
    echo
    cat "${project_list_file}"
    echo
    echo "## 说明"
    echo "- CI 会校验：此文件必须包含上述每一条路径文本。"
    echo "- 约定：Solution/Project requirements 均在 ${SOL_DIR}/ 下，不应在根目录出现 .*.requirements.md"
    echo
    echo "${AGENTIC_HEADER}"
    echo
    cat "${agentic_docs_file}"
  } > "${SOL_REQ}"
  echo "[req] wrote: ${SOL_REQ}"
}

refresh_section() {
  local header="$1"
  local section_file="$2"
  local tmp
  tmp="$(mktemp)"

  awk -v header="${header}" -v list_file="${section_file}" '
    function print_list() {
      while ((getline line < list_file) > 0) {
        print line
      }
      close(list_file)
    }
    {
      if ($0 == header) {
        found = 1
        in_section = 1
        print $0
        print ""
        print_list()
        print ""
        next
      }

      if (in_section == 1) {
        if ($0 ~ /^## /) {
          in_section = 0
          print $0
        }
        next
      }

      print $0
    }
    END {
      if (found == 0) {
        if (NR > 0) {
          print ""
        }
        print header
        print ""
        print_list()
        print ""
      }
    }
  ' "${SOL_REQ}" > "${tmp}"

  mv "${tmp}" "${SOL_REQ}"
  echo "[req] refreshed section: ${header}"
}

project_list_tmp="$(mktemp)"
build_project_list_file "${project_list_tmp}"
agentic_docs_tmp="$(mktemp)"
build_agentic_docs_file "${agentic_docs_tmp}"

# Build / refresh solution-level index
if [[ ! -f "${SOL_REQ}" || "${RAYMAN_FORCE_REBUILD:-0}" == "1" ]]; then
  write_solution_requirements "${project_list_tmp}" "${agentic_docs_tmp}"
else
  refresh_section "${PROJ_LIST_HEADER}" "${project_list_tmp}"
  refresh_section "${AGENTIC_HEADER}" "${agentic_docs_tmp}"
fi

rm -f "${project_list_tmp}"
rm -f "${agentic_docs_tmp}"
